x = np.linspace(0, 2*np.pi, 300)
y_sin = np.sin(x)
y_cos = np.cos(x)

plt.figure()
plt.plot(x, y_sin, 'r--', label='sin(x)', marker='o')
plt.plot(x, y_cos, 'b-', label='cos(x)', marker='x')
plt.title("Sine and Cosine Functions")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.grid(True)
plt.show()
